import { GalleryProject } from "@/types/gallery";

export const INITIAL_PROJECTS: GalleryProject[] = [
  {
    id: "proj-1",
    carModel: "Porsche 911 GT3 RS (992)",
    serviceCategory: "Keramikversiegelung",
    description: "3-Stufen Hochglanzpolitur zur Beseitigung aller Mikrokratzer, gefolgt von einer 2-schichtigen 9H Keramikversiegelung für maximalen Tiefenglanz und hydrophoben Abperleffekt.",
    beforeImage: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1400&q=85",
    afterImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85",
    visible: true,
    featured: true,
    duration: "24 Arbeitsstunden (3 Tage)",
    protection: "36 Monate Lackschutz-Garantie",
    tags: ["9H Keramik", "Lackkorrektur", "GT3 RS", "Hydrophobie"],
    createdAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "proj-2",
    carModel: "Mercedes-AMG GT R Pro",
    serviceCategory: "Lackaufbereitung",
    description: "Vollständige Beseitigung von Waschkratzern, Hologrammen und Baumharz-Rückständen. Mehrstufiges Polieren mit Schweizer High-End Schleifpasten und Carnauba-Hybridversiegelung.",
    beforeImage: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85",
    afterImage: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1400&q=85",
    visible: true,
    featured: true,
    duration: "18 Arbeitsstunden (2 Tage)",
    protection: "12 Monate Glanzversiegelung",
    tags: ["AMG GT", "Hologrammentfernung", "Spiegelglanz"],
    createdAt: "2026-03-10T12:00:00Z",
  },
  {
    id: "proj-3",
    carModel: "Audi RS6 Avant Performance",
    serviceCategory: "Innenraumreinigung",
    description: "Intensive Tiefenreinigung der Valcona-Lederpolster mit schonendem Dampfsauger, Alcantara-Faseraufrichtung, porentiefe Imprägnierung und Ozon-Neutralisierung zur Keimbeseitigung.",
    beforeImage: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=85",
    afterImage: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1400&q=85",
    visible: true,
    featured: true,
    duration: "8 Arbeitsstunden (1 Tag)",
    protection: "Lederversiegelung gegen Abrieb",
    tags: ["RS6", "Lederpflege", "Alcantara", "Ozonbehandlung"],
    createdAt: "2026-03-05T09:30:00Z",
  },
  {
    id: "proj-4",
    carModel: "BMW M4 CSL (G82)",
    serviceCategory: "Außenreinigung",
    description: "Schonende 2-Eimer Handwäsche mit pH-neutralem Schneeschaum, chemische Flugrost- & Teerentfernung, Tiefenreinigung der Carbon-Keramik-Bremssättel und Schmiedefelgen mit anschließender Versiegelung.",
    beforeImage: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1400&q=85",
    afterImage: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=85",
    visible: true,
    featured: false,
    duration: "6 Arbeitsstunden",
    protection: "Polymer-Detailer & Felgenschutz",
    tags: ["M4 CSL", "Handwäsche", "Felgenaufbereitung", "Carbonpflege"],
    createdAt: "2026-02-28T14:00:00Z",
  },
  {
    id: "proj-5",
    carModel: "Ferrari F8 Tributo",
    serviceCategory: "Keramikversiegelung",
    description: "Rosso Corsa Perfektion: Beseitigung aller Werks-Hologramme, Glaskantenversiegelung und 3-lagige 9H Graphen-Keramikbeschichtung mit extremer Chemikalienresistenz und Lotusblüteneffekt.",
    beforeImage: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1400&q=85",
    afterImage: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1400&q=85",
    visible: true,
    featured: true,
    duration: "30 Arbeitsstunden (4 Tage)",
    protection: "48 Monate Zertifizierter Schutz",
    tags: ["Ferrari", "Rosso Corsa", "9H Keramik", "Exoten"],
    createdAt: "2026-02-20T11:00:00Z",
  },
  {
    id: "proj-6",
    carModel: "Porsche Taycan Turbo S",
    serviceCategory: "Sonderaufbereitung",
    description: "Leasingrückläufer-Komplettaufbereitung: Schrammenbeseitigung im Einstiegsbereich, Dellenentfernung ohne Lackieren (Smart Repair), Beseitigung von Steinschlägen an der Frontschürze zur Vermeidung hoher Rückzahlungskosten.",
    beforeImage: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1400&q=85",
    afterImage: "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=1400&q=85",
    visible: true,
    featured: false,
    duration: "16 Arbeitsstunden (2 Tage)",
    protection: "TÜV / Dekra konforme Abnahme",
    tags: ["Leasingrückläufer", "Smart Repair", "Taycan", "Werterhalt"],
    createdAt: "2026-02-14T08:00:00Z",
  },
];
